import SideNav from "@/components/SideNav";
import { useAuth } from "@/context/AuthContext";
import { createClient } from "@/utils/supabase/client";
import { Geist, Geist_Mono } from "next/font/google";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Orange Bookstore Admin",
  description: "Generated by create next app",
};




export default async function RootLayout({ children }) {




  return (
        <div className="flex gap-4">
      <SideNav />
      <main className="flex-1">{children}</main>
    </div>
  );
}
